fastapi/typer

- docs/features.md
- docs/index.md
- docs/tutorial/first-steps.md
- docs/tutorial/intro.md
Hi! I just did a full check of all the documentation, fixed some typos and misunderstandings. :)
> Documentation full review 

- docs/css/custom.css
- docs/css/termynal.css
- docs/index.md
- docs/js/custom.js
- docs/js/termynal.js
- mkdocs.yml
:sparkles: Add [Ines' termynal](https://github.com/ines/termynal) with some customizations.
To automatically convert Markdown fenced code into pretty Termynals in docs.
> Add custom termynal handling for docs, with fenced code

- typer/completion.py
- typer/main.py
:sparkles: Add automatic completion options by default, if click-completion is installed
> Add automatic completion options by default, if click-completion is installed

- scripts/test.sh
- tests/test_tutorial/test_first_steps/test_tutorial002.py
- tests/test_tutorial/test_first_steps/test_tutorial003.py
- tests/test_tutorial/test_first_steps/test_tutorial004.py
- tests/test_tutorial/test_first_steps/test_tutorial005.py
- typer/testing.py
:heavy_check_mark: Fix testing tools, add first tests
> Fix testing tools, add first tests

- .coveragerc
- .gitignore
- docs/src/first_steps/tutorial006.py
- docs/tutorial/first-steps.md
- pyproject.toml
- tests/test_tutorial/test_first_steps/test_tutorial001.py
- tests/test_tutorial/test_first_steps/test_tutorial002.py
- tests/test_tutorial/test_first_steps/test_tutorial003.py
- tests/test_tutorial/test_first_steps/test_tutorial004.py
- tests/test_tutorial/test_first_steps/test_tutorial005.py
- tests/test_tutorial/test_first_steps/test_tutorial006.py
- typer/completion.py
- typer/main.py
:bug: :memo: Fix and document extracting help form docstring.
This should fix/related to https://github.com/tiangolo/typer/issues/3
> Fix and document extracting help form docstring

- typer/__init__.py
:fire: Clean exports from typer, remove unneeded Click components and add `Exit` exception to simplify usage.
> Clean exports from typer, remove unneeded Click components

- README.md
- docs/css/custom.css
- docs/index.md
- docs/js/custom.js
- docs/js/termynal.js
- docs/release-notes.md
- docs/src/options/tutorial001.py
- docs/src/options/tutorial002.py
- docs/src/options/tutorial003.py
- docs/src/options/tutorial004.py
- docs/src/options/tutorial005.py
- docs/src/options/tutorial006.py
- docs/tutorial/first-steps.md
- docs/tutorial/options.md
- mkdocs.yml
- tests/test_tutorial/test_options/test_tutorial001.py
- tests/test_tutorial/test_options/test_tutorial002.py
- tests/test_tutorial/test_options/test_tutorial003.py
- tests/test_tutorial/test_options/test_tutorial004.py
- tests/test_tutorial/test_options/test_tutorial005.py
- tests/test_tutorial/test_options/test_tutorial006.py
- typer/completion.py
- typer/main.py
- typer/models.py
:memo: :sparkles: Add docs for CLI Options with tests.
> Add docs for CLI Options with tests

- docs/css/custom.css
- docs/css/termynal.css
- docs/js/termynal.js
- docs/src/arguments/tutorial001.py
- docs/src/arguments/tutorial002.py
- docs/src/arguments/tutorial003.py
- docs/tutorial/arguments.md
- mkdocs.yml
- tests/test_tutorial/test_arguments/test_tutorial001.py
- tests/test_tutorial/test_arguments/test_tutorial002.py
- tests/test_tutorial/test_arguments/test_tutorial003.py
:memo: Add docs for CLI arguments.
> Add docs for CLI arguments

- tests/test_completion.py
- typer/completion.py
:white_check_mark: Add tests for completion.
> Add tests for completion

- docs/src/printing/tutorial001.py
- docs/src/printing/tutorial002.py
- docs/src/terminating/tutorial001.py
- docs/src/terminating/tutorial002.py
- docs/src/terminating/tutorial003.py
- docs/tutorial/first-steps.md
- docs/tutorial/printing.md
- docs/tutorial/terminating.md
- mkdocs.yml
- tests/test_tutorial/test_terminating/test_tutorial001.py
- tests/test_tutorial/test_terminating/test_tutorial002.py
- tests/test_tutorial/test_terminating/test_tutorial003.py
- typer/__init__.py
- typer/colors.py
:memo: :sparkles: Add colors module and docs for printing and terminating, including tests.
> Add colors module and docs for printing and terminating.

- docs/src/parameter_types/path/tutorial001.py
- docs/tutorial/parameter-types/path.md
- tests/test_tutorial/test_parameter_types/test_path/test_tutorial001.py
> Update path docs

- docs/src/app_dir/tutorial001.py
- docs/tutorial/app-dir.md
- mkdocs.yml
:memo: Add docs for get_app_dir()
> Add docs for get_app_dir()

- docs/src/commands/callback/tutorial001.py
- docs/src/commands/callback/tutorial002.py
- docs/src/commands/callback/tutorial003.py
- docs/src/commands/callback/tutorial004.py
- docs/src/commands/one_or_multiple/tutorial001.py
- docs/src/commands/one_or_multiple/tutorial002.py
- docs/tutorial/commands/callback.md
- docs/tutorial/commands/one-or-multiple.md
- tests/test_tutorial/test_commands/test_callback/test_tutorial001.py
- tests/test_tutorial/test_commands/test_callback/test_tutorial002.py
- tests/test_tutorial/test_commands/test_callback/test_tutorial003.py
- tests/test_tutorial/test_commands/test_callback/test_tutorial004.py
- tests/test_tutorial/test_commands/test_one_or_multiple/test_tutorial001.py
- tests/test_tutorial/test_commands/test_one_or_multiple/test_tutorial002.py
- typer/main.py
:memo: Extend commands' docs for callbacks and one vs multiple commands.
> Extend commands' docs

- docs/src/parameter_types/bool/tutorial001.py
- docs/src/parameter_types/bool/tutorial002.py
- docs/src/parameter_types/bool/tutorial003.py
- docs/src/parameter_types/bool/tutorial004.py
- docs/src/parameter_types/number/tutorial003.py
- docs/tutorial/parameter-types/bool.md
- docs/tutorial/parameter-types/number.md
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial003.py
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial004.py
- tests/test_tutorial/test_parameter_types/test_number/test_tutorial003.py
:memo: Add extra docs and tests for param types.
> Add extra docs and tests for param types.

- docs/src/multiple_values/arguments_with_multiple_values/tutorial001.py
- docs/src/multiple_values/multiple_options/tutorial001.py
- docs/src/multiple_values/multiple_options/tutorial002.py
- docs/src/multiple_values/options_with_multiple_values/tutorial001.py
- docs/tutorial/multiple-values/arguments-with-multiple-values.md
- docs/tutorial/multiple-values/index.md
- docs/tutorial/multiple-values/multiple-options.md
- docs/tutorial/multiple-values/options-with-multiple-values.md
- tests/test_tutorial/test_multiple_values/test_arguments_with_multiple_values/test_tutorial001.py
- tests/test_tutorial/test_multiple_values/test_multiple_options/test_tutorial001.py
- tests/test_tutorial/test_multiple_values/test_multiple_options/test_tutorial002.py
- tests/test_tutorial/test_multiple_values/test_options_with_multiple_values/test_tutorial001.py
- typer/main.py
:memo: :sparkles: :bug: Add docs for CLI parameters with multiple values, with tests and bug fixes.
> Add docs for CLI parameters with multiple values, with tests and bug fixes

- README.md
- docs/contributing.md
- docs/css/custom.css
- docs/features.md
- docs/index.md
- docs/tutorial/arguments.md
- docs/tutorial/first-steps.md
- docs/tutorial/index.md
- docs/tutorial/prompt.md
- docs/tutorial/subcommands/callback-override.md
- docs/tutorial/subcommands/index.md
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial003.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial004.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial005.py
- tests/test_tutorial/test_parameter_types/test_path/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_path/test_tutorial002.py
:memo: Refactor docs with internal links
> Refactor docs with internal links

- README.md
- docs/index.md
- docs/tutorial/arguments.md
- docs/tutorial/commands/index.md
- docs/tutorial/commands/one-or-multiple.md
- docs/tutorial/first-steps.md
- docs/tutorial/options/required.md
- docs/tutorial/parameter-types/datetime.md
- docs/tutorial/parameter-types/enum.md
- docs/tutorial/parameter-types/index.md
- docs/tutorial/parameter-types/number.md
- docs/tutorial/parameter-types/path.md
- docs/tutorial/parameter-types/uuid.md
- pyproject.toml
- tests/test_tutorial/test_arguments/test_tutorial001.py
- tests/test_tutorial/test_commands/test_index/test_tutorial001.py
- tests/test_tutorial/test_first_steps/test_tutorial002.py
- tests/test_tutorial/test_first_steps/test_tutorial003.py
- tests/test_tutorial/test_options/test_required/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_datetime/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_enum/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_index/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_number/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_number/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_path/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_uuid/test_tutorial001.py
- typer/main.py
- typer/models.py
- typer/testing.py
:sparkles: Add support for Click 7.1.1
> Add support for Click 7.1.1

- README.md
- docs/features.md
- docs/index.md
- docs/tutorial/first-steps.md
- docs/tutorial/index.md
- docs/typer-cli.md
- mkdocs.yml
- scripts/test.sh
> Docs for Typer CLI

- tests/test_completion/test_completion_install.py
- tests/test_completion/test_completion_install_source.py
- typer/completion.py
:bug: Fix Zsh completion install
> Fix Zsh completion install

- docs/src/progressbar/tutorial004.py
In the tutorial, the length of the progress bar is set to 1000 and the update was mistakenly set to 2500. The update should be 1/4 of the length given that the loop runs for 4 iterations. This commit sets the update amount to 250 which better showcases the feature.
> :pencil2: fix typo in progressbar/tutorial004.py

- docs/contributing.md
- scripts/docs-live.sh
- tests/test_completion/test_completion.py
- tests/test_completion/test_completion_install.py
- typer/completion.py
:bug: Fix Bash completion install to `.bashrc` and update Windows docs.
`.bash_completion` seems to be specific to a third-party package.
> Fix Bash completion install to .bashrc

- tests/test_completion/test_completion.py
- tests/test_completion/test_completion_install.py
- tests/test_completion/test_completion_install_source.py
- typer/completion.py
:sparkles: Do not show an error on completion eval if the program is not installed
> Do not show an error on completion eval if the program is not installed

- .gitignore
- docs/contributing.md
- docs/js/custom.js
- mkdocs.yml
:heavy_plus_sign: Upgrade Material-Mkdocs
> Upgrade Material-Mkdocs

- docs/tutorial/printing.md
:memo: Add emphasis note about using `typer.echo()` instead of `print()`.
To help to add extra clarity to situations like https://github.com/tiangolo/typer/issues/84
> Add emphasis note about using typer.echo instead of print

- pyproject.toml
- tests/test_others.py
- typer/completion.py
- typer/main.py
- typer/models.py
- typer/utils.py
:sparkles: Add support for forward references.
Related to #43
> Add support for forward references

- docs/tutorial/arguments.md
Minor correction in the CLI Arguments tutorial page. Changed users to use-cases under other uses section.
> Minor correction in CLI Arguments page

- docs/tutorial/arguments.md
- docs/tutorial/options/autocompletion.md
Adding clarification at the end of the arguments tutorial for clarification.
> Quick clarification in arguments docs

- docs/tutorial/package.md
📝 Add docs for `__main__.py` passing `prog_name` to callable Typer app.
> 📝 Add docs for __main__.py

- docs/tutorial/parameter-types/datetime.md
As mentioned in https://github.com/tiangolo/typer/pull/116
Not sure if this is too simple of an addition
> Docs date string format update

- docs/tutorial/options/name.md
- docs/tutorial/options/version.md
- docs/tutorial/parameter-types/bool.md
- docs/tutorial/parameter-types/path.md
- docs/typer-cli.md
- docs_src/multiple_values/multiple_options/tutorial001.py
- docs_src/multiple_values/options_with_multiple_values/tutorial001.py
- docs_src/options/version/tutorial001.py
- docs_src/options/version/tutorial002.py
- docs_src/options/version/tutorial003.py
- docs_src/parameter_types/bool/tutorial002.py
- docs_src/parameter_types/path/tutorial001.py
- docs_src/testing/app01/main.py
Addressing #125 : all CLI arguments / options with default value of None declared using Optional generics
> Support for Optional added to docs for CLI Argument and Options

- .github/workflows/build-docs.yml
👷 Disable installing MkDocs Insiders in forks
> 👷 Disable installing MkDocs Insiders in forks

- .github/workflows/build-docs.yml
👷 Fix Material for MkDocs install in CI
> 👷 Fix Material for MkDocs install in CI

- tests/assets/type_error_no_rich_short_disable.py
- tests/assets/type_error_rich_pretty_disable.py
- tests/assets/type_error_rich_short_disable.py
- tests/test_tracebacks.py
- typer/main.py
- typer/models.py
✨ Allow configuring pretty errors when creating the Typer instance
> ✨ Allow configuring pretty errors when creating the Typer instance

- typer/rich_utils.py
🐛 Fix setting `FORCE_TERMINAL` with colors
> 🐛 Fix setting `FORCE_TERMINAL` with colors

- typer/main.py
🎨 Fix type annotations for `get_group`
> 🎨 Fix type annotations for `get_group`

- .github/workflows/test.yml
- pyproject.toml
➕ Add extra Material for MkDocs deps for docs
> ➕ Add extra Material for MkDocs deps for docs

- .coveragerc
- .github/workflows/smokeshow.yml
- .github/workflows/test.yml
- README.md
- docs/index.md
- pyproject.toml
- scripts/test-cov-html.sh
- scripts/test.sh
👷 Move from pytest-cov to coverage and Codecov to Smokeshow
> 👷 Move from pytest-cov to coverage and Codecov to Smokeshow

- .github/workflows/test.yml
- pyproject.toml
- scripts/test-cov-html.sh
- scripts/test.sh
➕ Bring back pytest-cov because coverage can't detect pytest-xdist
> ➕ Bring back pytest-cov because coverage can't detect pytest-xdist

- .github/workflows/test.yml
- scripts/test.sh
> 🔧 Tweak pytest coverage

- docs/tutorial/parameter-types/datetime.md
**Issue:**
Documentation claims `formats receives a list of strings with the date formats that would be passed to datetime.strptime()` however the actual link is pointing to `date.strftime()` as can be seen [here](https://typer.tiangolo.com/tutorial/parameter-types/datetime/#custom-date-format)
**Fix**
Replaced the incorrect link by one thats pointing to `datetime.strptime()`
> ✏ Fix link in docs to `datetime.strptime()`

- docs/tutorial/commands/help.md
Markown -> Markdown.
(Thanks for this awesome library).
> 📝 Fix typo in docs at `docs/tutorial/commands/help.md`

- docs/tutorial/commands/index.md
- docs/tutorial/options-autocompletion.md
- docs_src/options_autocompletion/tutorial001.py
- docs_src/options_autocompletion/tutorial002.py
- docs_src/options_autocompletion/tutorial003.py
- docs_src/options_autocompletion/tutorial004.py
- docs_src/options_autocompletion/tutorial005.py
- docs_src/options_autocompletion/tutorial006.py
- docs_src/options_autocompletion/tutorial007.py
- docs_src/options_autocompletion/tutorial008.py
- docs_src/options_autocompletion/tutorial009.py
- mkdocs.yml
- pyproject.toml
- tests/test_completion/test_completion.py
- tests/test_completion/test_completion_install.py
- tests/test_completion/test_completion_show.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial002.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial003.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial004.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial007.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial008.py
- tests/test_tutorial/test_options_autocompletion/test_tutorial009.py
- typer/main.py
✨ Make `typer.run()` not add completion scripts by default, it only makes sense in installed apps
This currently only adds noise to simple scripts.
> ✨ Make `typer.run()` not add completion scripts by default, it only makes sense in installed apps

- tests/test_tutorial/test_subcommands/test_tutorial003.py
✅ Add extra tests just for coverage because monkeypatching with strange imports confuses coverage
> ✅ Add extra tests just for coverage because monkeypatching with strange imports confuses coverage

- docs/tutorial/package.md
From poetry's docs: 
>Some shells may treat square braces ([ and ]) as special characters. It is suggested to always quote arguments containing these characters to prevent unexpected shell expansion.
https://python-poetry.org/docs/cli/#add
> ✏️ Add quotes to package name that includes brackets in docs

- tests/test_tutorial/test_subcommands/test_tutorial001.py
- tests/test_tutorial/test_subcommands/test_tutorial003.py
When packaging Typer for openSUSE I ran into errors because the tutorial
scripts were unable to import their colocated modules. Curiously this
only seems to be occurring when these scripts are run via coverage, as
they are in the tests. Them being run via coverage however also prevents
just changing the working directory for the script runs, as then the
coverage file would end up in the wrong directory.
Curiously, I have not been able to reproduce this issue on openSUSE Leap
but only seen it on openSUSE Tumbleweed. Thus, there might be something
weird with the Python stack or the coverage version on Tumbleweed.
However, as the same PYTHONPATH-patching is also done for the tests of
the tutorial code that run it directly and not as a subprocess, I think
it is just consistent to also do this …
> 👷‍♂️ Ensure the `PYTHONPATH` is set properly when testing the tutorial scripts

- docs/tutorial/arguments/default.md
- docs/tutorial/arguments/envvar.md
- docs/tutorial/arguments/help.md
- docs/tutorial/arguments/optional.md
- docs/tutorial/commands/index.md
- docs/tutorial/first-steps.md
- docs/tutorial/multiple-values/arguments-with-multiple-values.md
- docs/tutorial/multiple-values/options-with-multiple-values.md
- docs/tutorial/options/help.md
- docs/tutorial/options/name.md
- docs/tutorial/options/required.md
- docs/tutorial/options/version.md
- docs/tutorial/parameter-types/bool.md
- docs/tutorial/parameter-types/datetime.md
- docs/tutorial/parameter-types/enum.md
- docs/tutorial/parameter-types/index.md
- docs/tutorial/parameter-types/number.md
📝 Remove obsolete references to `--install-completion` for `typer.run()` scripts
> 📝 Remove obsolete references to `--install-completion` for `typer.run()` scripts

- .github/workflows/build-docs.yml
👷 Install MkDocs Material Insiders only when secrets are available, for Dependabot
> 👷 Install MkDocs Material Insiders only when secrets are available, for Dependabot

- docs/tutorial/arguments/optional.md
> ✏ Fix typo in `docs/tutorial/arguments/optional.md`

- docs/tutorial/options/name.md
> ✏ Fix typo in `docs/tutorial/options/name.md`

- docs/tutorial/exceptions.md
Happened to notice this doubled `would` when reading the docs, opening a tiny PR to fix it.
> ✏ Fix typo in `docs/tutorial/exceptions.md`

- docs/tutorial/package.md
I was a bit confused at first sight about where the `main.py` file was in that tree.
> 📝 Update docs for building a package, file structure example

- typer/params.py
Merely a comment in code to help developers understand the difference between the different `overload` definitions (as it took me some time to figure out)
> 💡 Add comments to document overload definitions in code

- docs/tutorial/using-click.md
- tests/test_tutorial/test_using_click/test_tutorial003.py
In the [documentation](https://typer.tiangolo.com/tutorial/using-click/#including-a-click-app-in-a-typer-app), an example is given of a Typer app that includes a Click app. The example reads
> // Notice we have both subcommands, top and hello
But for the user to actually see this, they should call `main.py` with `--help` specifically. I've updated the docs accordingly, and added a unit test to ensure that both commands are indeed shown in the help function.
> 📝 Update docs example for a Typer/Click group to make new subcommands explicit

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- pyproject.toml
- requirements-docs.txt
- requirements-tests.txt
- requirements.txt
🔧 Refactor package manager, move from Flit to PDM, remove private pip extras for `test`, `doc`, `dev`
> 🔧 Refactor package manager, move from Flit to PDM, remove private pip extras for `test`, `doc`, `dev`

- mypy.ini
- pyproject.toml
- requirements-tests.txt
- scripts/lint.sh
- typer/core.py
- typer/main.py
> 🔧 Upgrade mypy and config

- .github/workflows/redistribute.yml
- .github/workflows/test-redistribute.yml
- .github/workflows/test.yml
- pyproject.toml
- scripts/test.sh
🔧 Explicitly include testing files in sdist for redistributors (e.g. OpenSUSE) and add CI to test redistribution
> 🔧 Explicitly include testing files in sdist for redistributors (e.g. OpenSUSE) and add CI to test redistribution

- .github/workflows/publish.yml
👷 Do not use the cache for dependencies when publishing to PyPI
> 👷 Do not use the cache for dependencies when publishing to PyPI

- docs/tutorial/typer-command.md
- tests/assets/cli/multiapp-docs-title.md
- tests/test_cli/test_doc.py
- typer/cli.py
✨ Add support for `typer ./someprogram.py utils docs --title`
Migrated from https://github.com/tiangolo/typer-cli/pull/111
> ✨ Add support for `typer ./someprogram.py utils docs --title`

- docs/tutorial/commands/callback.md
- docs/tutorial/commands/options.md
- docs/tutorial/multiple-values/arguments-with-multiple-values.md
- docs/tutorial/multiple-values/options-with-multiple-values.md
- docs/tutorial/options/prompt.md
- docs/tutorial/parameter-types/bool.md
- docs/tutorial/parameter-types/datetime.md
- docs/tutorial/parameter-types/enum.md
- docs/tutorial/parameter-types/index.md
- docs/tutorial/parameter-types/number.md
- docs/tutorial/parameter-types/uuid.md
PR https://github.com/tiangolo/typer/pull/760 removed Click 7 support, and accordingly removed the Click 7 console messages from the unit tests (e.g. see [here](https://github.com/tiangolo/typer/commit/5bea9cf205df92cb24526f63ac6c6dc9d2b888c2#diff-780b1cd026f4279bd0ec0358daee6b9320bc503c68b0b0a099f27a2bd313b5f5)). This PR updates all the log messages in the documentation to the Click 8 variants as well.
> 📝 Update console output with Click 8 messages

- .github/DISCUSSION_TEMPLATE/questions.yml
- Fix a broken link that was missing a `[`
- Fix a typo
> 🔧 Fix typo in Github template

- tests/test_rich_utils.py
- typer/rich_utils.py
When taking the `max` of the list of commands, define a `default` value to guard against calling `max` on an empty list, which would raise an error. (this is also how I had it in the original [suggestion](https://github.com/tiangolo/typer/pull/567#discussion_r1553956210))
Fixes https://github.com/PrefectHQ/prefect/issues/12617
Fixes https://github.com/tiangolo/typer/discussions/795
> 🐛 Fix Rich formatting with no commands

- tests/test_completion/test_completion.py
- tests/test_completion/test_completion_install.py
Ensure that the test suite runs properly on Windows by:
- adding quotes when paths can have spaces or backslashes
- using `Pathlib` to automatically parse the correct path separator, rather than relying on the literal string `"/"`
Related PR: https://github.com/tiangolo/typer/pull/809
> ✅ Generalize test suite to run on Windows

- .github/workflows/test.yml
- pyproject.toml
- tests/test_completion/test_completion.py
- tests/test_tutorial/test_commands/test_help/test_tutorial004.py
- tests/test_tutorial/test_commands/test_help/test_tutorial004_an.py
- tests/test_tutorial/test_commands/test_help/test_tutorial005.py
- tests/test_tutorial/test_commands/test_help/test_tutorial005_an.py
- tests/test_tutorial/test_commands/test_help/test_tutorial006.py
- tests/test_tutorial/test_commands/test_help/test_tutorial007.py
- tests/test_tutorial/test_commands/test_help/test_tutorial007_an.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial004.py
- tests/test_tutorial/test_parameter_types/test_file/test_tutorial004_an.py
- tests/utils.py
- typer/_completion_shared.py
> ✅ Add CI configs to run tests on Windows and MacOS

- .github/workflows/build-docs.yml
- docs/index.md
- mkdocs.insiders.yml
- mkdocs.maybe-insiders.yml
- mkdocs.yml
- scripts/build-docs.sh
- scripts/clean.sh
- scripts/docs-live.sh
- scripts/docs.py
- scripts/test-files.sh
🔧 Update MkDocs configs and docs build setup
> 🔧 Update MkDocs configs and docs build setup

- docs/contributing.md
- scripts/docker/Dockerfile
- scripts/docker/compose.yaml
📝 Add docs and scripts to test completion in different shells
> 📝 Add docs and scripts to test completion in different shells

- docs/tutorial/commands/index.md
- docs_src/commands/index/tutorial004.py
- tests/assets/cli/multiapp-docs-title.md
- tests/assets/cli/multiapp-docs.md
- tests/test_tutorial/test_commands/test_index/test_tutorial004.py
- typer/core.py
Fixes #933 
Click's `Group` class specifically [orders](https://github.com/pallets/click/blob/main/src/click/core.py#L1684) the items alphabetically:
```
def list_commands(self, ctx: Context) -> list[str]:
"""Returns a list of subcommand names in the order they should appear."""
return sorted(self.commands)
```
For `TyperGroup`, we override this behaviour and remove the `sorted` function. This works, because during creation of the group, the commands are kept in a list as they get declared, so `self.commands` has the original order.
> ✨ Show help items in order of definition

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/smokeshow.yml
- .github/workflows/test.yml
- requirements-github-actions.txt
> 👷 Use uv in CI

- typer/rich_utils.py
The docstring was out-of-date with the actual implementation.
> 📝 Update the docstring of the `_make_rich_text` method

- scripts/test.sh
- tests/test_completion/test_completion.py
- tests/test_completion/test_completion_install.py
- tests/test_others.py
- tests/utils.py
As discussed in https://github.com/fastapi/typer/pull/866#issuecomment-2316421622, introducing a specific env var `_TYPER_RUN_INSTALL_COMPLETION_TESTS` that needs to be set before `--install-completion` tests are run. This env var is set for tests on the CI, but would usually not be set when users run tests locally. This is to ensure no side effects or failing tests happen locally. Fixes #413.
Thanks to @rokbot for raising this issue in #866!
> ✅ Only run completion installation tests when the env var `_TYPER_RUN_INSTALL_COMPLETION_TESTS` is set

- tests/test_completion/colon_example.py
- tests/test_completion/test_completion_option_colon.py
- typer/_completion_classes.py
Allow for colons in zsh completion values and descriptions, related to #162 
Note that because of the [`startswith` check](https://github.com/fastapi/typer/blob/master/typer/core.py#L90) escaping the completion options in the client side is not an option, as a value that includes a `:` for `incomplete` in will not pass this check.
Note that we need two levels of esacping, one for zsh, and one to preserve the escape for zsh
Tested by updating the `demo.py` example in the linked issue to the following:
```python
import typer
image_desc = [
("alpine:latest", "latest alpine image"),
("alpine:hello", "fake image: for testing"),
("nvidia/cuda:10.0-devel-ubuntu18.04", ""),
]
def _complete(incomplete: str) -> str:
for (image, desc) in image_desc:
if image.startswith(incomplete):
yield image, desc …
```
> 🐛 Allow colon in zsh autocomplete values and descriptions

- typer/rich_utils.py
🐛 Fix printing HTML from Rich output
It seems capturing was not working, I think it did at https://github.com/fastapi/typer/pull/847 because tests were passing, but it seems it's no longer working.
Using `io.StringIO()` seems to be the suggested way in an issue: https://github.com/Textualize/rich/issues/247#issuecomment-678699266
> 🐛 Fix printing HTML from Rich output

- docs/tutorial/subcommands/name-and-help.md
- docs_src/subcommands/name_help/tutorial002.py
- docs_src/subcommands/name_help/tutorial003.py
- docs_src/subcommands/name_help/tutorial004.py
- docs_src/subcommands/name_help/tutorial005.py
- docs_src/subcommands/name_help/tutorial007.py
- docs_src/subcommands/name_help/tutorial008.py
- tests/test_callback_warning.py
- tests/test_tutorial/test_subcommands/test_name_help/test_tutorial007.py
- typer/main.py
While working on #1037 (allowing `add_typer` to extend an app), we found that callbacks are sometimes used to implicitly get a group's name.
This would happen in cases like this:
```python
import typer
app = typer.Typer()
users_app = typer.Typer()
app.add_typer(users_app)
@users_app.callback()
def callback():
...
@users_app.command()
def create(name: str):
print(f"Creating user: {name}")
```
<details>
<summary>Output for the above</summary>
```text
[14:47:30] ➜ python example.py --help
Usage: example.py [OPTIONS] COMMAND [ARGS]...
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --install-completion          Install completion for the current shell. …
```
> 🔥 Remove auto naming of groups added via `add_typer` based on the group's callback function name

- docs/tutorial/commands/one-or-multiple.md
- docs/tutorial/commands/options.md
- docs/tutorial/first-steps.md
- docs_src/commands/one_or_multiple/tutorial002.py
- tests/test_tutorial/test_commands/test_one_or_multiple/test_tutorial002.py
I think I saw a couple of typos or inconsistencies in the tutorial:
- Grammar error in `commands/one-or-multiple.md`
- Wrong command listed in `command/options.md`
- What looks to be missing words in `first-steps.md` (I doubt a typer "parameter" or "argument" refers to a python function)
Thanks a lot for your work on this great tool. I hope this helps!
> 📝 Fix minor inconsistencies and typos in tutorial

- .github/workflows/test.yml
Limit the ubuntu version in the test suite to `22.04`, which still supports Python 3.7 while the current `ubuntu-latest` image doesn't anymore.
> 💚 Fix test matrix for Python 3.7

- docs/tutorial/options-autocompletion.md
- docs/tutorial/options/callback-and-context.md
- Fixed the same typo twice
- Removed an unnecessary word which was hindering interpretability of the sentence
> ✏️ Fix small typos in the tutorial documentation

- pyproject.toml
Compatibility for Click >= 8.2 is worked on here: https://github.com/fastapi/typer/pull/1222 , but there are a couple of unsolved issues there still.
So this pin will solve current apps for now, and a future release will have compatibility with the latest Click.
> 📌 Pin Click to < 8.2, compatibility for Click >= 8.2 will be added in a future version

- tests/test_others.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial001.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial001_an.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial003.py
- tests/test_tutorial/test_multiple_values/test_arguments_with_multiple_values/test_tutorial002.py
- tests/test_tutorial/test_multiple_values/test_arguments_with_multiple_values/test_tutorial002_an.py
- tests/test_tutorial/test_parameter_types/test_datetime/test_tutorial001.py
- tests/test_tutorial/test_terminating/test_tutorial003.py
- tests/test_tutorial/test_using_click/test_tutorial003.py
- tests/test_tutorial/test_using_click/test_tutorial004.py
✅ Refactor tests for compatibility with Click 8.2
> ✅ Refactor tests for compatibility with Click 8.2

- tests/test_rich_utils.py
- typer/core.py
- typer/main.py
- typer/rich_utils.py
rich.markup is used to escape strings when rendering help texts.
This fixes a regression introduced by https://github.com/fastapi/typer/pull/1128
> 🐛 Make sure `rich.markup` is imported when rendering help text

- pyproject.toml
This is temporary, until we straighten out the issues with `UNSET` vs `None`, as introduced by Click 8.3.0. 
Proper fix will be in PR https://github.com/fastapi/typer/pull/1333
> ⬇️ Restrict Click to below 8.3.0 to handle changes in the new version

- typer/core.py
- typer/rich_utils.py
Yesterday's release of [Click 8.3.0](https://github.com/pallets/click/releases/tag/8.3.0) has [introduced](https://github.com/pallets/click/pull/3030) a new internal variable `UNSET` to differentiate between (truly) unset values and user-provided `None` values. As a consequence, the method `Parameter.value_is_missing` in `click.core` now checks for this `UNSET` value instead of for `None`. 
This results in bugs when using the current Typer with Click 8.3.0+, because a required, unset parameter would be `None` in Typer (and not the new `UNSET` value) and would eventually get the default value instead of throwing an exception.
For instance:
```
@app.command()
def main(name: str):
print(f"Hello {name}")
```
would result in a print `"Hello None"` when calling it without any arguments.
1. A …
> 👽️ Ensure compatibility with Click 8.3.0 by restoring the original `value_is_missing` function

- pyproject.toml
- tests/assets/type_error_no_rich.py
- tests/assets/type_error_no_rich_short_disable.py
- tests/test_corner_cases.py
- tests/test_tutorial/test_arguments/test_envvar/test_tutorial001.py
- tests/test_tutorial/test_arguments/test_envvar/test_tutorial001_an.py
- tests/test_tutorial/test_arguments/test_help/test_tutorial001.py
- tests/test_tutorial/test_arguments/test_help/test_tutorial001_an.py
- tests/test_tutorial/test_arguments/test_help/test_tutorial008.py
- tests/test_tutorial/test_arguments/test_help/test_tutorial008_an.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial001.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial001_an.py
- tests/test_tutorial/test_arguments/test_optional/test_tutorial003.py
- tests/test_tutorial/test_commands/test_callback/test_tutorial001.py
- tests/test_tutorial/test_options/test_required/test_tutorial001.py
- tests/test_tutorial/test_options/test_required/test_tutorial001_an.py
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial002.py
- tests/test_tutorial/test_parameter_types/test_bool/test_tutorial002_an.py
- tests/test_tutorial/test_parameter_types/test_number/test_tutorial001.py
- tests/test_tutorial/test_parameter_types/test_number/test_tutorial001_an.py
- tests/test_tutorial/test_terminating/test_tutorial003.py
- typer/cli.py
- typer/core.py
- typer/main.py
- typer/rich_utils.py
To avoid regressions like #1294 occurring in the future, I propose a different way of lazy-loading rich using `importlib.util.find_spec`. I also propose using the `TID` Ruff rules to enforce the lazy-loading logic in the future.
This provides a framework to systematically apply other lazy-loading migrations safely.
> ✅ Use Ruff rules to ensure safe lazy-loading of `rich`

- README.md
- docs/index.md
This PR adds a note in the README explaining that Typer treats single-command CLIs differently than multi-command CLIs.
This behavior can be surprising for new users (like myself), because calling the command by name (e.g., python cli.py hello Camila) results in an error when only one command is defined — Typer silently expects python cli.py Camila instead.
While this is explained in the full documentation, the README contains a similar example and is often the first place beginners look. A brief clarification here could help save users some confusion — especially those coming from FastAPI, where the number of wrapped functions doesn’t affect how the app is invoked.
Related issues:
#315 - this PR directly addresses confusion raised here.
#445 - is tangentially related in that it also …
> 📝 Clarify single-command vs multi-command behaviour in README

- typer/testing.py
The type of the Click `env` parameter is `Mapping[str, str | None] | None`. This can be used to "delete" an environment variable.
> ✨ Allow setting an environment variable to `None` in `CliRunner.invoke`
