fastapi/typer

README.md, docs/features.md, docs/index.md, docs/tutorial/index.md
:memo: Update docs with references to --install-completion and use subcommand everywhere instead of sub-command for consistency with Click
=> Update docs with references to --install-completion

tests/test_completion.py
:white_check_mark: Update completion tests, checking for printed message
=> Update completion tests, checking for printed message

docs/src/prompt/tutorial001.py, docs/src/prompt/tutorial002.py, docs/src/prompt/tutorial003.py, docs/tutorial/prompt.md, mkdocs.yml, tests/test_tutorial/test_prompt/test_tutorial001.py, tests/test_tutorial/test_prompt/test_tutorial002.py, tests/test_tutorial/test_prompt/test_tutorial003.py
:memo: Add docs for interactive prompts.
=> Add docs for interactive prompts

docs/src/progressbar/tutorial001.py, docs/src/progressbar/tutorial002.py, docs/src/progressbar/tutorial003.py, docs/src/progressbar/tutorial004.py, docs/tutorial/progressbar.md, mkdocs.yml, tests/test_tutorial/test_commands/test_help/test_tutorial002.py
:memo: Add docs for progress bars.
=> Add docs for progress bars

docs/src/app_dir/tutorial001.py, docs/src/launch/tutorial001.py, docs/src/launch/tutorial002.py, docs/tutorial/app-dir.md, docs/tutorial/launch.md, mkdocs.yml
:memo: Add docs for launching applications/files.
=> Add docs for launching applications/files

typer/main.py
:fire: Remove unused code for argument param declarations
=> Remove unused code for argument param declarations

tests/test_others.py
:white_check_mark: Add 4 extra tests for edge cases.
=> Add 4 extra tests for edge cases

README.md, docs/css/custom.css, docs/features.md, docs/help-typer.md, docs/index.md, docs/tutorial/app-dir.md, docs/tutorial/arguments.md, docs/tutorial/index.md, docs/tutorial/multiple-values/options-with-multiple-values.md, docs/tutorial/options/name.md, docs/tutorial/options/required.md, docs/tutorial/parameter-types/datetime.md, docs/tutorial/parameter-types/enum.md, docs/tutorial/parameter-types/file.md, docs/tutorial/parameter-types/index.md, docs/tutorial/parameter-types/path.md, docs/tutorial/parameter-types/uuid.md, docs/tutorial/printing.md, docs/tutorial/progressbar.md, docs/tutorial/prompt.md, docs/tutorial/subcommands/callback-override.md, docs/tutorial/subcommands/index.md
:art: Tweak external links' format.
=> Tweak external links' format

.github/workflows/deploy-docs.yml
:construction_worker: Add GitHub action to deploy docs
=> Add GitHub action to deploy docs

mkdocs.yml
:sparkles: Add support for Mermaid JS visualizations.
=> Add support for mermaid visualizations

.github/workflows/deploy-docs.yml
:arrow_up: Upgrade Netlify deploy action
=> Upgrade Netlify deploy action

docs/contributing.md
=> Add contributing guide

docs/alternatives.md
:memo: Add docs about alternatives and inspiration
=> Add docs about alternatives and inspiration

docs/tutorial/subcommands/add-typer.md, docs/tutorial/subcommands/nested-subcommands.md, docs/tutorial/subcommands/single-file.md
:bug: Fix docs format with `hl_lines`
=> Fix docs format with hl_lines

docs/src/using_click/tutorial001.py, docs/src/using_click/tutorial002.py, docs/src/using_click/tutorial003.py, docs/src/using_click/tutorial004.py, docs/tutorial/using-click.md, mkdocs.yml, tests/test_tutorial/test_using_click/test_tutorial003.py, tests/test_tutorial/test_using_click/test_tutorial004.py
:memo: Add docs for using Click with Typer.
=> Add docs for using Click with Typer

docs/tutorial/package.md, docs/tutorial/using-click.md, mkdocs.yml
:memo: Add docs section, build a package from scratch
=> Add docs section, build a package from scratch

docs/features.md, docs/tutorial/testing.md, tests/test_completion/test_completion.py, tests/test_completion/test_completion_install.py
:white_check_mark: Add coverage instructions to tests
=> Add coverage instructions to tests

README.md, docs/index.md
:art: Update testing coverage badge
=> Update testing coverage badge

typer/completion.py
:bug: Fix Fish completion script
=> Fix Fish completion script

.github/workflows/issue-manager.yml
=> 🔧 Update issue-manager

README.md, docs/index.md
Correcting some typos in the readme.
=> Readme correct

.github/dependabot.yml
➕ Add Dependabot, try and see how it behaves with Flit
=> ➕ Add Dependabot, try and see how it behaves with Flit

pyproject.toml
=> 📌 Pin dependencies

.github/workflows/publish.yml, .github/workflows/test.yml, .travis.yml, scripts/deploy.sh
👷 Add GitHub Actions, move from Travis
=> 👷 Add GitHub Actions, move from Travis

.gitignore, scripts/test.sh, tests/test_completion/test_completion_install.py
✅ Report coverage in XML to support GitHub Actions.
=> ✅ Report coverage in XML

.github/FUNDING.yml, docs/help-typer.md
=> 🔧 Add sponsors docs and badge

.github/workflows/deploy-docs.yml
=> 👷 Update docs CI name

.github/workflows/latest-changes.yml
👷 Add GitHub Action Latest Changes
=> 👷 Add GitHub Action Latest Changes

.github/workflows/test.yml
=> 👷 Enable tests for Python 3.9

SECURITY.md
=> 📝 Add Security policy

.github/workflows/publish.yml
👷 Update publish GitHub action
=> 👷 Update publish GitHub action

mkdocs.yml, pyproject.toml
⬆️ Upgrade MkDocs Material, MDX-Include, and MkDocs structure
=> ⬆️ Upgrade MkDocs Material, MDX-Include, and MkDocs structure

.github/workflows/test.yml
💚 Only test on push when on master, avoid duplicate CI runs from PRs
=> 💚 Only test on push when on master, avoid duplicate CI runs from PRs

docs/overrides/main.html, mkdocs.yml
📝 Add Jina's QA Bot to the docs to help people that want to ask quick questions
This supersedes https://github.com/tiangolo/typer/pull/363 with a couple of small tweaks. It's in an independent PR instead of on top of the original as I can't commit directly to that one.
=> 📝 Add Jina's QA Bot to the docs to help people that want to ask quick questions

.github/workflows/test.yml
⬆️ Upgrade Codecov GitHub Action
=> ⬆️ Upgrade Codecov GitHub Action

.github/workflows/build-docs.yml
=> 👷 Clear MkDocs Insiders cache

.github/workflows/test.yml, pyproject.toml
=> ✨ Add support for Python 3.11, tests in CI and official marker

.github/workflows/build-docs.yml, .github/workflows/preview-docs.yml, .github/workflows/test.yml, scripts/zip-docs.sh
👷 Refactor CI artifact upload/download for docs previews
=> 👷 Refactor CI artifact upload/download for docs previews

.pre-commit-config.yaml
🔧 Update pre-commit, Python version, isort version
Related to https://github.com/PyCQA/isort/issues/2077 and https://github.com/PyCQA/isort/pull/2078
=> 🔧 Update pre-commit, Python version, isort version

.github/DISCUSSION_TEMPLATE/questions.yml
🔧 Add GitHub Discussion templates for questions
=> 🔧 Add GitHub Discussion templates for questions

docs/help-typer.md
📝 Update docs about helping Typer
=> 📝 Update docs about helping Typer

docs/tutorial/commands/help.md, docs_src/commands/help/tutorial004.py, docs_src/commands/help/tutorial005.py, tests/test_tutorial/test_commands/test_help/test_tutorial004.py, tests/test_tutorial/test_commands/test_help/test_tutorial005.py
Just a small spelling fix - cheers! :)
=> ✏ Fix spelling (shinny -> shiny)

docs/tutorial/parameter-types/custom-types.md, docs_src/parameter_types/custom_types/tutorial001_an.py, docs_src/parameter_types/custom_types/tutorial002_an.py, tests/test_tutorial/test_parameter_types/test_custom_types/test_tutorial001_an.py, tests/test_tutorial/test_parameter_types/test_custom_types/test_tutorial002_an.py, typer/params.py
📝 Update docs examples for custom param types using `Annotated`, fix overloads for `typer.Argument`
=> 📝 Update docs examples for custom param types using `Annotated`, fix overloads for `typer.Argument`

.github/workflows/deploy-docs.yml
=> 👷 Deploy docs to Cloudflare

.github/workflows/build-docs.yml
👷 Update build docs CI cache paths
=> 👷 Update build docs CI cache paths

CITATION.cff
🔧 Add `CITATION.cff` file for academic citations
=> 🔧 Add `CITATION.cff` file for academic citations

docs/tutorial/commands/context.md
Updated a link to the newest stable version of click
=> 📝 Update link in docs to the newest stable version of click

.github/workflows/test.yml
=> 👷 Add alls-green to CI

.github/workflows/issue-manager.yml
👷 Upgrade issue-manager GitHub Action
=> 👷 Upgrade issue-manager GitHub Action

.github/workflows/smokeshow.yml
👷 Upgrade Smokeshow GitHub action
=> 👷 Upgrade Smokeshow GitHub action

.github/workflows/build-docs.yml
👷 Fix install MkDocs Insiders only when available
=> 👷 Fix install MkDocs Insiders only when available

mkdocs.insiders.yml
🔧 Temporarily disable social plugin while a MkDocs issue is handled
https://github.com/squidfunk/mkdocs-material/issues/6983
=> 🔧 Temporarily disable social plugin while a MkDocs issue is handled

mkdocs.insiders.yml
🔧 Update MkDocs Material, enable plugins
=> 🔧 Update MkDocs Material, enable plugins

.github/workflows/test-redistribute.yml, requirements-tests.txt
👷 Tweak CI for test-redistribute, add needed env vars for slim
=> 👷 Tweak CI for test-redistribute, add needed env vars for slim

.github/workflows/build-docs.yml, .github/workflows/deploy-docs.yml, .github/workflows/smokeshow.yml, .github/workflows/test.yml
👷 Update GitHub Actions to upload and download artifacts
=> 👷 Update GitHub Actions to upload and download artifacts

scripts/lint.sh
=> 🔨 Update lint script

.gitignore
🙈 Add MkDocs Material cache to gitignore
=> 🙈 Add MkDocs Material cache to gitignore

requirements-docs.txt
➖ Do not install jieba for MkDocs Material as there are no chinese translations
=> ➖ Do not install jieba for MkDocs Material as there are no chinese translations

mkdocs.yml
=> 🔧 Enable dark mode for docs

mkdocs.yml
🔧 Enable MkDocs Material features
=> 🔧 Enable MkDocs Material features

mkdocs.yml
🔧 Enable auto dark mode from system
=> 🔧 Enable auto dark mode from system

.github/workflows/build-docs.yml, docs/css/termynal.css, docs/js/custom.js, docs/js/termynal.js, mkdocs.insiders.yml, mkdocs.yml, requirements-docs-insiders.txt, requirements-docs.txt, scripts/docs.py, scripts/mkdocs_hooks.py
=> 👷 Upgrade build docs configs

data/members.yml, docs/about/index.md, docs/css/custom.css, docs/management-tasks.md, docs/management.md, docs/resources/index.md, docs/tutorial/index.md, mkdocs.yml
📝 Add docs for team and repo management
=> 📝 Add docs for team and repo management

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/privileged.yml, CITATION.cff, README.md, docs/help-typer.md, docs/index.md, docs/management-tasks.md, docs/tutorial/subcommands/index.md, mkdocs.yml, pyproject.toml, typer-cli/README.md
📝 Update docs links, from tiangolo to new fastapi org
=> 📝 Update docs links, from tiangolo to new fastapi org

.github/workflows/labeler.yml
👷 Update labeler GitHub Actions permissions and dependencies
=> 👷 Update labeler GitHub Actions permissions and dependencies

.github/labeler.yml, .github/workflows/labeler.yml
👷 Update labeler GitHub Action to add only one label
=> 👷 Update labeler GitHub Action to add only one label

.gitignore
🙈 Remove extra line in .gitignore
=> 🙈 Remove extra line in .gitignore

README.md, docs/contributing.md, docs/environment-variables.md, docs/index.md, docs/tutorial/arguments/envvar.md, docs/tutorial/index.md, docs/tutorial/install.md, docs/virtual-environments.md, mkdocs.yml
📝 Add docs for virtual environments, environment variables, and update contributing
=> 📝 Add docs for virtual environments, environment variables, and update contributing

docs/contributing.md
✏️ Fix typo in `docs/contributing.md`
=> ✏️ Fix typo in `docs/contributing.md`

.github/workflows/issue-manager.yml
=> 👷 Fix issue-manager

docs/virtual-environments.md
✏️ Fix a typo in `docs/virtual-environments.md`
=> ✏️ Fix a typo in `docs/virtual-environments.md`

scripts/docker/Dockerfile, scripts/docker/compose.yaml
🔨 Pre-install dependencies in Docker so that testing in Docker is faster
=> 🔨 Pre-install dependencies in Docker so that testing in Docker is faster

typer/rich_utils.py
Break out from https://github.com/fastapi/typer/pull/815 to allow the other PR to focus more on the important issue of how exactly to parse markdown.
=> ✏️ Fix typo in function name `_make_rich_text`

.github/workflows/build-docs.yml
🔧 Update build-docs filter patterns
=> 🔧 Update build-docs filter patterns
